const level1 = new Level(
  [new Chickensmall(), new Chicken(), new Chicken(), new Chicken()],
  [new Cloud(), new Cloud()],

  [
    new BackgroundObject("./imgs/5_background/layers/air.png", -1438, 0),
    new BackgroundObject("./imgs/5_background/layers/3_third_layer/2.png", -1438, 0),
    new BackgroundObject("./imgs/5_background/layers/2_second_layer/2.png", -1438, 0, 0),
    new BackgroundObject("./imgs/5_background/layers/1_first_layer/2.png", -1438, 0),
    new BackgroundObject("./imgs/5_background/layers/air.png", -719, 0),
    new BackgroundObject("./imgs/5_background/layers/3_third_layer/2.png", -719, 0),
    new BackgroundObject("./imgs/5_background/layers/2_second_layer/2.png", -719, 0),
    new BackgroundObject("./imgs/5_background/layers/1_first_layer/2.png", -719, 0),
    new BackgroundObject("./imgs/5_background/layers/air.png", 0),
    new BackgroundObject("./imgs/5_background/layers/3_third_layer/1.png", 0),
    new BackgroundObject("./imgs/5_background/layers/2_second_layer/1.png", 0),
    new BackgroundObject("./imgs/5_background/layers/1_first_layer/1.png", 0),
    new BackgroundObject("./imgs/5_background/layers/air.png", 719),
    new BackgroundObject("./imgs/5_background/layers/3_third_layer/2.png", 719),
    new BackgroundObject("./imgs/5_background/layers/2_second_layer/2.png", 719),
    new BackgroundObject("./imgs/5_background/layers/1_first_layer/2.png", 719),
    new BackgroundObject("./imgs/5_background/layers/air.png", 719 * 2),
    new BackgroundObject("./imgs/5_background/layers/3_third_layer/1.png", 719 * 2),
    new BackgroundObject("./imgs/5_background/layers/2_second_layer/1.png", 719 * 2),
    new BackgroundObject("./imgs/5_background/layers/1_first_layer/1.png", 719 * 2),
    new BackgroundObject("./imgs/5_background/layers/air.png", 719 * 3),
    new BackgroundObject("./imgs/5_background/layers/3_third_layer/2.png", 719 * 3),
    new BackgroundObject("./imgs/5_background/layers/2_second_layer/2.png", 719 * 3),
    new BackgroundObject("./imgs/5_background/layers/1_first_layer/2.png", 719 * 3),
  ]
);
